-- Facility Experience QA -- buildings master list + expanded roles

CREATE TABLE IF NOT EXISTS buildings (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  location   TEXT NOT NULL,
  division   TEXT NOT NULL,
  area       TEXT NOT NULL,
  name       TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_buildings_division ON buildings(division);
CREATE INDEX IF NOT EXISTS idx_buildings_area ON buildings(area);

INSERT INTO buildings (location, division, area, name) VALUES
  ('DHAHRAN', 'CAOSD', 'Core Area', 'MA BLDG #177'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'SAA BLDG #1755'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'NA BLDG #175'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'SA BLDG #177 150'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'EA BLDG #176'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'AL-MUNIRAH BLDG #149'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'EX BLDG #728'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'EX BLDG #729'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'BLDG #137'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'BLDG #137 ANNEX'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'BLDG #490'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'TOWER BLDG #730'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'TOWER BLDG #731'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'OSS BLDG# 9160'),
  ('DHAHRAN', 'CAOSD', 'Core Area', 'BLDG #112'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'WP BLDG #2201'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'WP BLDG #2202'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'WP BLDG #2203'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'WP BLDG #325'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'MSB BLDG #1965'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'TEC BLDG #2288'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'WAREHOUSE BLDG #2064'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'BLDG #1835'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'BLDG #1841'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3150'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3105'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3106'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3107'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3108'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3118'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3119'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3132'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3133'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3134'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3135'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3136'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3137'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'BLDG #3140'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'BLDG #3169'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'BLDG #3040'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3060 MAIN (UD)'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3060-A'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3060-B'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG 3060-C'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3060-D'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3060-E'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3060-F'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3060-G'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'LIP BLDG #3060-J'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'BLDG #215'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'OSD WAREHOUSE BLDG #3000'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'DHP BLDG - 1'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'DHP BLDG - 2'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'DHP BLDG - 3'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'DHP BLDG - 4'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'DHP BLDG - 5'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'DHP BLDG - 6'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'DHP BLDG - 7'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'DHP BLDG - 8'),
  ('DHAHRAN', 'CAOSD', 'Satelite Area', 'DHP BLDG - 9'),
  ('DHAHRAN', 'OOSD', 'CA Remote', 'U&FSD MAIN BLDG #9020'),
  ('DHAHRAN', 'OOSD', 'CA Remote', 'PEST CONTROL BLDG #9060'),
  ('DHAHRAN', 'OOSD', 'CA Remote', 'GARDENING AND SANITATION 9061'),
  ('DHAHRAN', 'OOSD', 'CA Remote', 'FMD Foremen Offices 7005A'),
  ('DHAHRAN', 'OOSD', 'CA Remote', 'OASIS AVENUE 4655-4657'),
  ('DHAHRAN', 'OOSD', 'CA Remote', 'AEC BLDG #9135'),
  ('DHAHRAN', 'OOSD', 'AMAAD', 'Parcel 3 - Tower 2 ( Office 2)'),
  ('DHAHRAN', 'OOSD', 'AMAAD', 'Parcel 3 - Tower 4 (Office 4)'),
  ('DHAHRAN', 'OOSD', 'AMAAD', 'Parcel 4 - Tower 1 (Office 5)'),
  ('DHAHRAN', 'OOSD', 'AMAAD', 'Parcel 4 - Tower 2 (Office 6)'),
  ('DHAHRAN', 'OOSD', 'AMAAD', 'Parcel 4 - Tower 3 (Office 7)'),
  ('DAMMAM', 'OOSD', 'DOC', 'DOC Annex BLDG #7014'),
  ('DAMMAM', 'OOSD', 'DOC', 'DOC BLDG #7013'),
  ('DHAHRAN', 'NPOSD', 'Al-Midra Unit', 'AL-MIDRA TOWER 3304'),
  ('DHAHRAN', 'NPOSD', 'North Park Unit', 'North Park I 3300'),
  ('DHAHRAN', 'NPOSD', 'North Park Unit', 'North Park II 33001'),
  ('DHAHRAN', 'NPOSD', 'North Park Unit', 'North Park III 3302'),
  ('DHAHRAN', 'NPOSD', 'North Park Unit', 'Auditorium 3305'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', 'Mechanical Shop - 3189'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', '3193 D&W'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', '3191'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', 'Mobility Park 4– 3087'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', 'Mobility Park 3– 3015'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', 'Mobility Park 1– 9153'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', 'Mobility Park 2– 3017'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', '3274'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', '3270'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', '3273'),
  ('DHAHRAN', 'NPOSD', 'NP Satellite Buildings', '3275'),
  ('TANAJIB', 'NAOSD', 'Tanajib Unit', 'Tanajib BLDG #5300'),
  ('TANAJIB', 'NAOSD', 'Tanajib Unit', 'Tanajib BLDG #6100'),
  ('TANAJIB', 'NAOSD', 'Tanajib Unit', 'Tanajib BLDG #3306'),
  ('Safaniyah', 'NAOSD', 'Tanajib Unit', 'Safaniyah BLDG #998'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #997'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #995'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #994'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #1050'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #1013'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #551'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #1017'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #4125'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #820'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #820A'),
  ('RAS TANURA', 'NAOSD', 'Ras Tanura Unit', 'RT BLDG #1121'),
  ('Juaymah', 'NAOSD', 'Ras Tanura Unit', 'Juaymah BLDG #2050'),
  ('Berri', 'NAOSD', 'Ras Tanura Unit', 'Berri BLDG #1050'),
  ('ABQAIQ', 'SAOSD', 'ABQ Unit', 'ABQ BLDG #900'),
  ('ABQAIQ', 'SAOSD', 'ABQ Unit', 'ABQ BLDG #1495'),
  ('ABQAIQ', 'SAOSD', 'ABQ Unit', 'ABQ BLDG #1114'),
  ('ABQAIQ', 'SAOSD', 'ABQ Unit', 'ABQ BLDG #9-311'),
  ('ABQAIQ', 'SAOSD', 'ABQ Unit', 'ABQ BLDG # 9-311-1'),
  ('ABQAIQ', 'SAOSD', 'ABQ Unit', 'ABQ BLDG # 991'),
  ('ABQAIQ', 'SAOSD', 'ABQ Unit', 'ABQ BLDG #927'),
  ('ABQAIQ', 'SAOSD', 'ABQ Unit', 'ABQ BLDG #1140'),
  ('ABQAIQ', 'SAOSD', 'ABQ Unit', 'ABQ BLDG #9-512'),
  ('ABQAIQ', 'SAOSD', 'ABQ Unit', 'ABQ BLDG #5-276'),
  ('SHEDGUM', 'SAOSD', 'MUB Unit', 'Shedgum BLDG #3009'),
  ('MUBARRAZ', 'SAOSD', 'MUB Unit', 'MUB BLDG #8875'),
  ('MUBARRAZ', 'SAOSD', 'MUB Unit', 'MUB BLDG #8876'),
  ('MUBARRAZ', 'SAOSD', 'MUB Unit', 'MUB BLDG #8877'),
  ('UDHAILIYAH', 'SAOSD', 'UDH Unit', 'UDH BLDG #1020'),
  ('UDHAILIYAH', 'SAOSD', 'UDH Unit', 'UDH BLDG #1610'),
  ('UDHAILIYAH', 'SAOSD', 'UDH Unit', 'UDH BLDG #1025'),
  ('UDHAILIYAH', 'SAOSD', 'UDH Unit', 'UDH BLDG #599'),
  ('UDHAILIYAH', 'SAOSD', 'UDH Unit', 'UDH BLDG #2099'),
  ('UDHAILIYAH', 'SAOSD', 'UDH Unit', 'UDH BLDG #1001'),
  ('Riyadh', 'RYOSD', 'MS Area', 'Bldg. # 200'),
  ('Riyadh', 'RYOSD', 'MS Area', 'MSA'),
  ('Riyadh', 'RYOSD', 'Refinery Unit', 'Bldg. # 305'),
  ('Riyadh', 'RYOSD', 'Refinery Unit', 'Bldg. # 330'),
  ('Riyadh', 'RYOSD', 'Refinery Unit', 'Bldg. # 340'),
  ('Riyadh', 'RYOSD', 'Admin. Area', 'Najd Shamal 900'),
  ('Riyadh', 'RYOSD', 'Admin. Area', 'Najd Janoud 910'),
  ('Riyadh', 'RYOSD', 'Takassousi Unit', 'Bldg. # 2000'),
  ('Riyadh', 'RYOSD', 'Takassousi Unit', 'Bldg. # 2010'),
  ('Riyadh', 'RYOSD', 'Takassousi Unit', 'Bldg. # 2020'),
  ('Riyadh', 'RYOSD', 'Takassousi Unit', 'Bldg. # 2030'),
  ('Riyadh', 'RYOSD', 'Arat Unit', 'ARAT BLDG #3000'),
  ('Riyadh', 'RYOSD', 'Al-Rabwah Compound', 'BLDG # 1'),
  ('Riyadh', 'RYOSD', 'Al-Rabwah Compound', 'BLDG #9');

-- Expand roles: admin/inspector -> the five named roles
UPDATE qa_users SET role = 'quality_admin' WHERE role = 'admin';
UPDATE qa_users SET role = 'quality_auditor' WHERE role = 'inspector';
